// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID          int32
	FullName    string
	PhoneNumber string
	Email       string
	Password    string
	IsActive    bool
	CreatedAt   pgtype.Timestamp
}

type Dispatcher struct {
	ID           int32
	FullName     string
	PhoneNumber  string
	Email        string
	Password     string
	PrimaryAlert string
	IsActive     bool
	CreatedAt    pgtype.Timestamp
}

type Driver struct {
	ID                int32
	FullName          string
	PhoneNumber       string
	Email             string
	PermanentAddress  string
	LicenseNumber     string
	LicenseValidUntil pgtype.Date
	PrimaryAlert      string
	IsAvailable       bool
	IsActive          bool
	CreatedAt         pgtype.Timestamp
}

type FuelUsage struct {
	ID         int32
	VehicleID  int32
	JobID      pgtype.Int4
	FuelFilled float64
	FuelCost   float64
	BillProof  string
	OdoReading int32
	RecordedAt pgtype.Timestamp
}

type Job struct {
	ID            int32
	VehicleID     int32
	DriverID      int32
	StartLocation string
	EndLocation   string
	StartTime     pgtype.Timestamp
	EndTime       pgtype.Timestamp
	IsDelayed     bool
	Status        string
	CreatedAt     pgtype.Timestamp
}

type LiveLocation struct {
	ID         int32
	VehicleID  int32
	JobID      pgtype.Int4
	Latitude   float64
	Longitude  float64
	RecordedAt pgtype.Timestamp
}

type Notification struct {
	ID        int32
	UserID    int32
	JobID     pgtype.Int4
	Channel   string
	Message   string
	IsRead    bool
	CreatedAt pgtype.Timestamp
}

type Setting struct {
	ID        int32
	Key       string
	Value     string
	CreatedAt pgtype.Timestamp
}

type Vehicle struct {
	ID                  int32
	Make                string
	Model               string
	RegistrationNumber  string
	Capacity            int32
	YearOfPurchase      int32
	TotalKmsDriven      int32
	LastServicedOn      pgtype.Date
	CurrentMileage      int32
	InsuranceValidUntil pgtype.Date
	CurrentStatus       string
	CreatedAt           pgtype.Timestamp
}
